version: "3.6"
services:
  service-issue-tracker-backend:
    image: service-issue-tracker-backend:0.0.5
    container_name: service-issue-tracker-backend
    hostname: service-issue-tracker-backend
    volumes:
      - ./pm2.json:/pm2.json
    ports:
      - 8299:8299
    networks:
      - issue-tracker
networks:
  issue-tracker:
    external: true  